# Generated by Django 4.1.5 on 2023-04-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pill_tracker_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermedication',
            old_name='number_of_pills',
            new_name='total_quantity',
        ),
        migrations.AlterField(
            model_name='usermedication',
            name='dosage',
            field=models.CharField(max_length=50),
        ),
    ]
