# Generated by Django 4.1.5 on 2023-03-31 02:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=50)),
                ('medication_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('dosage', models.CharField(max_length=20)),
                ('intake_quantity', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('refill_date', models.DateField()),
                ('times_per_day', models.PositiveSmallIntegerField(default=1)),
                ('time_of_first_med', models.TimeField()),
                ('number_of_pills', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('rxcui', models.CharField(max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('taken', models.BooleanField(default=False)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pill_tracker_api.usermedication')),
            ],
        ),
        migrations.CreateModel(
            name='HealthInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField()),
                ('blood_pressure', models.CharField(blank=True, max_length=255, null=True)),
                ('height', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=50)),
                ('blood_sugar', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
