# Generated by Django 4.1.5 on 2023-04-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pill_tracker_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedication',
            name='dosage',
            field=models.CharField(max_length=50),
        ),
    ]
