# Generated by Django 4.1.7 on 2023-03-21 00:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pill_tracker_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedication',
            name='number_of_pills',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
