# Generated by Django 4.1.5 on 2023-03-21 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pill_tracker_api', '0002_alter_usermedication_user'),
        ('pill_tracker_api', '0002_usermedication_number_of_pills'),
    ]

    operations = [
    ]
