# Generated by Django 3.2.4 on 2023-04-03 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pill_tracker_api', '0002_alter_usermedication_dosage'),
        ('pill_tracker_api', '0002_rename_number_of_pills_usermedication_total_quantity_and_more'),
    ]

    operations = [
    ]
